pipeline {
	agent any
	stages {

		stage('Creating Kubernetes Cluster') {
			steps {
				withAWS(region:'us-west-2', credentials:'awscredentials') {
					sh '''
						eksctl create cluster \
						--name capstonecluster \
						--version 1.14 \
						--nodegroup-name ng \
						--node-type t2.small \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami auto \
						--region us-west-2 \
						--zones us-west-2a \
						--zones us-west-2b \
						--zones us-west-2c \
					'''
				}
			}
		}

		stage('Configuring kubectl') {
			steps {
				withAWS(region:'us-west-2', credentials:'awscredentials') {
					sh '''
						aws eks --region us-west-2 update-kubeconfig --name capstonecluster
					'''
				}
			}
		}

	}
}
