---
kind: Service
apiVersion: v1
metadata:
    name: bluegreenLB
    labels:
        app: bluegreenLB
spec:
    ports:
        - port: 8000
          targetPort: 80
    selector:
        app: greenctl
    type: LoadBalancer
